services:
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2gb'
    environment:
      - SE_EVENT_BUS_HOST=172.18.0.3
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge